name: RPGItems
main: think.rpgitems.RPGItems
description: "RPGItems"
version: ${version}
depend: [NyaaCore,Vault]
softdepend: [WorldGuard,NyaaUtils,PlaceholderAPI,Residence,MythicMobs]
authors: [Taiterio,cyilin,RecursiveG,Librazy,Clexus]
website: "https://github.com/NyaaCat/RPGItems-reloaded"
database: false
api-version: 1.21.5
libraries:
  - 'com.udojava:EvalEx:2.7'
  - 'net.bytebuddy:byte-buddy:1.12.16'

commands:
  rpgitem:
    description: RPGItems' Admin Command Handler
    permission: rpgitem
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"
  rpgitems:
    description: RPGItems' User Command Handler
    permission: rpgitems
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  rpgitem.allowenchant.new:
    default: op
  rpgitem.allowenchant.old:
    default: op
  rpgitem.updateitem:
    default: op

  rpgitems.tomodel:
    default: false
  rpgitems.info:
    default: false